language: node_js
node_js:
- 8.5.0
script:
  - "npm run lint"
  - "npm run test"
deploy:
  provider: heroku
  edge: true
  api_key:ef788613-db41-43e6-a7e1-8d8e954fed88
  app: NodeProject
  on:
    repo: Li-Mengke/NodeProject
