language: node_js
node_js:
- 8.5.0
script:
  - "npm run lint"
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: "2997cced-cafb-4e75-a76e-96efca4d40fb"
  app: NodeProject
  on:
    repo: Li-Mengke/NodeProject
