language: node_js
node_js:
- 8.5.0
script:
  - "npm run lint"
  - "npm run test"
deploy:
  provider: heroku
  edge: true
  api_key:
    secure:"33df37a4-6207-4a00-85d7-8b8190201f12"
  app: NodeProject
  on:
    repo: Li-Mengke/NodeProject
